before:
  hooks:
    - go mod tidy
    - go run main.go --version

builds:
  - id: cast
    main: ./main.go
    binary: cast
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-v{{ .Version }}"
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: packages
    vendor: frostyeti
    homepage: https://github.com/frostyeti/cast
    maintainer: frostyeti
    description: A powerful task runner and automation tool
    license: MIT
    file_name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-v{{ .Version }}"
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    bindir: /usr/bin

# Docker builds can be enabled later
# dockers:
#   - image_templates:
#       - "frostyeti/cast:{{ .Tag }}"
#       - "frostyeti/cast:latest"
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
