[tools]
go = '1.26.1'
deno = '2.7.4'

[tasks.build_ui]
description = "Build the Svelte UI into static files"
dir = "ui"
run = """
  bun install
  bun run build
"""

[tasks.publish]
depends = ["build_ui"]
description = "Build the cast CLI with embedded UI and publish to local bin"
run = """
  go build -o ./bin/cast ./main.go
  cp ./bin/cast "$HOME/.local/bin/cast"
"""

[tasks.build]
depends = "build_ui"
run =  """
  go build -o ./bin/cast ./main.go
"""