name: Vulnerability Scan

on:
  schedule:
    - cron: '48 6 * * 1'
  workflow_dispatch:

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Setup environment
        run: |
          go mod download
          go mod tidy

      - name: Run govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
